version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./public/content:/usr/share/nginx/html/content
    restart: unless-stopped 